2024-08-26 08:20:19,783 - user_api - DEBUG - Logging is configured and directory exists.
2024-08-26 08:21:21,951 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2024-08-26 08:21:21,953 - httpx - DEBUG - load_verify_locations cafile='/usr/local/lib/python3.9/site-packages/certifi/cacert.pem'
2024-08-26 08:21:21,972 - httpcore.connection - DEBUG - connect_tcp.started host='data_api' port=8000 local_address=None timeout=5.0 socket_options=None
2024-08-26 08:21:21,974 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7faea7b383d0>
2024-08-26 08:21:21,974 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'GET']>
2024-08-26 08:21:21,974 - httpcore.http11 - DEBUG - send_request_headers.complete
2024-08-26 08:21:21,974 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'GET']>
2024-08-26 08:21:21,974 - httpcore.http11 - DEBUG - send_request_body.complete
2024-08-26 08:21:21,974 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'GET']>
2024-08-26 08:21:22,007 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 401, b'Unauthorized', [(b'date', b'Mon, 26 Aug 2024 08:21:21 GMT'), (b'server', b'uvicorn'), (b'www-authenticate', b'Basic'), (b'content-length', b'30'), (b'content-type', b'application/json')])
2024-08-26 08:21:22,008 - httpx - INFO - HTTP Request: GET http://data_api:8000/categories "HTTP/1.1 401 Unauthorized"
2024-08-26 08:21:22,008 - httpcore.http11 - DEBUG - receive_response_body.started request=<Request [b'GET']>
2024-08-26 08:21:22,008 - httpcore.http11 - DEBUG - receive_response_body.complete
2024-08-26 08:21:22,008 - httpcore.http11 - DEBUG - response_closed.started
2024-08-26 08:21:22,008 - httpcore.http11 - DEBUG - response_closed.complete
2024-08-26 08:21:22,009 - httpcore.connection - DEBUG - close.started
2024-08-26 08:21:22,009 - httpcore.connection - DEBUG - close.complete
